version: '3.8'

services:
  app:
    build: .
    container_name: flask_laboratory
    environment:
      - FLASK_ENV=development
      - FLASK_APP=index.py
    command: sh -c "ls -R /app && flask run --host=0.0.0.0 --port=5000"

